# Generated by Django 5.0.3 on 2024-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banking',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banking',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
