# Generated by Django 5.0.3 on 2024-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0003_account_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_creation',
            name='user',
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Adhaar_Card_Number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Pan_Card_Number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Permanant_Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Personal_Image',
            field=models.ImageField(null=True, upload_to='static/Images/Personal_Image'),
        ),
        migrations.AddField(
            model_name='account_creation',
            name='Resdential_Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='account_creation',
            name='Adhaar_Card_Image',
            field=models.ImageField(null=True, upload_to='static/Images/Adhaar_Card'),
        ),
        migrations.AlterField(
            model_name='account_creation',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account_creation',
            name='Pan_Card_Image',
            field=models.ImageField(null=True, upload_to='static/Images/Pan_Card_Image'),
        ),
    ]
