# Generated by Django 5.0.3 on 2024-03-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0004_remove_account_creation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_creation',
            name='Account_Number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
