# Generated by Django 5.0.3 on 2024-03-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0005_account_creation_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_creation',
            name='Basic_Amount',
            field=models.IntegerField(null=True),
        ),
    ]
