# Generated by Django 5.0.3 on 2024-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0006_account_creation_basic_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_creation',
            name='Passowrd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
