# Generated by Django 5.0.3 on 2024-04-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0007_account_creation_passowrd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_creation',
            old_name='Passowrd',
            new_name='Password',
        ),
    ]
