# Generated by Django 5.0.3 on 2024-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0008_rename_passowrd_account_creation_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Id', models.IntegerField(null=True)),
            ],
        ),
    ]
