# Generated by Django 5.0.3 on 2024-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_Login', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Account_Number_Reciever',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Account_Number_Sender',
            field=models.IntegerField(null=True),
        ),
    ]
